databases:
  - name: postgres
    ipAllowList: []
    databaseName: <%= ENV['POSTGRES_DB'] %>
    user: <%= ENV['POSTGRES_USER'] %>

services:
  - type: web
    name: <%= ENV['SERVICES_KEY'] %>
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false