# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production
      POSTGRES_DB: ENV['POSTGRES']
      POSTGRES_USER: ENV['POSTGRES_USER']
      POSTGRES_PASSWORD: ENV['POSTGRES_PASSWORD']
      DATABASE_URL: ENV['DATABASE_URL']

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true